%    SegArray implementation of CEIL.
%    B = CEIL(A)
%    Emulates full array behavior of CEIL; returns a SegArray.
%    (use HELP CEIL for details)

% GISTIC software version 2.0
% Copyright (c) 2011 Gad Getz, Rameen Beroukhim, Craig Mermel, 
% Jen Dobson, Steve Schumacher, Nico Stransky, Mike Lawrence, 
% Gordon Saksena, Michael O'Kelly, Barbara Tabak
% All Rights Reserved.
%
% See the accompanying file LICENSE.txt for licensing details.

function B = ceil(A)
% (code generated by unarray.pl)
B = A;
try
    B.vals = ceil(A.vals);
catch me
    throwAsCaller(me);
end
