%    SegArray implementation of ISCHAR.
%    B = ISCHAR(A)
%    Emulates normal behavior of ISCHAR.
%    (see HELP ISCHAR for details)

% GISTIC software version 2.0
% Copyright (c) 2011 Gad Getz, Rameen Beroukhim, Craig Mermel, 
% Jen Dobson, Steve Schumacher, Nico Stransky, Mike Lawrence, 
% Gordon Saksena, Michael O'Kelly, Barbara Tabak
% All Rights Reserved.
%
% See the accompanying file LICENSE.txt for licensing details.

function B = ischar(A)
% (code generated by unary.pl)
    try
        B = ischar(A.vals);
    catch me
        throwAsCaller(me);
    end
end
