%    SegArray implementation of ISNUMERIC.
%    B = ISNUMERIC(A)
%    Emulates normal behavior of ISNUMERIC.
%    (see HELP ISNUMERIC for details)

% GISTIC software version 2.0
% Copyright (c) 2011 Gad Getz, Rameen Beroukhim, Craig Mermel, 
% Jen Dobson, Steve Schumacher, Nico Stransky, Mike Lawrence, 
% Gordon Saksena, Michael O'Kelly, Barbara Tabak
% All Rights Reserved.
%
% See the accompanying file LICENSE.txt for licensing details.

function B = isnumeric(A)
% (code generated by unary.pl)
    try
        B = isnumeric(A.vals);
    catch me
        throwAsCaller(me);
    end
end
