%    SegArray implementation of LOG2.
%    B = LOG2(A)
%    Emulates full array behavior of LOG2; returns a SegArray.
%    (use HELP LOG2 for details)

% GISTIC software version 2.0
% Copyright (c) 2011 Gad Getz, Rameen Beroukhim, Craig Mermel, 
% Jen Dobson, Steve Schumacher, Nico Stransky, Mike Lawrence, 
% Gordon Saksena, Michael O'Kelly, Barbara Tabak
% All Rights Reserved.
%
% See the accompanying file LICENSE.txt for licensing details.

function B = log2(A)
% (code generated by unarray.pl)
B = A;
try
    B.vals = log2(A.vals);
catch me
    throwAsCaller(me);
end
