function display_D_heatmap(D)
%DISPLAY_D_HEATMAP display raw data heatmap with genomic scale
  % create figure

% GISTIC software version 2.0
% Copyright (c) 2011 Gad Getz, Rameen Beroukhim, Craig Mermel, 
% Jen Dobson, Steve Schumacher, Nico Stransky, Mike Lawrence, 
% Gordon Saksena, Michael O'Kelly, Barbara Tabak
% All Rights Reserved.
%
% See the accompanying file LICENSE.txt for licensing details.

  disp_p=struct('x',struct('sizes',[1 0.1 0.03 3 0.6 0.6 0.6],'gaps',[1 1 1 1 1 1 1 2],'border',0.2),...
             'y',struct('sizes',[ 0.2 3.5 0.08],'gaps',[2 1 1 2],'border',0.2),...
             'items',...
             {{...
                 {1,2:3,'ssupacc','vert',6},...
                 {2:3,1,'ssuplegend',1,8,6,0,0.3},...
                 {1,4,'ssupdat'},...
                 {2,4,'dataorig',[-1 1]},...
                 {2,2,'chrn','vert',6,-0.5},...
                 {2,3,'chrcyto'},...
                 {3,4,'colorbar','horizontal',[1+63/4*(0:4)],{'-1','-0.5','0','0.5','1'},6},...
              }});

  display_D(D,[],[],disp_p);
