function disp_p=get_disp_defaults(dt)


% GISTIC software version 2.0
% Copyright (c) 2011 Gad Getz, Rameen Beroukhim, Craig Mermel, 
% Jen Dobson, Steve Schumacher, Nico Stransky, Mike Lawrence, 
% Gordon Saksena, Michael O'Kelly, Barbara Tabak
% All Rights Reserved.
%
% See the accompanying file LICENSE.txt for licensing details.

if nargin==0
  dt='datsup';
end

switch dt
 case 'dends_with_dists'
  disp_p.x.sizes=[0.7 0.01 0.3 2 0.1 1 0.1]; 
  % gdend, gsupdat, gacc, data, sdist colorbar, gdist colorbar
  disp_p.x.gaps=[1 0 1 1 1 1 1 1];
  % no gap between gdend and gsupdat
  disp_p.x.border=0.05;
  
  disp_p.y.sizes=[0.7 0.2 0.3 1 0.1 2];
  % sdend, ssupdat, sdesc, data, data colorbar, sdist
  disp_p.y.gaps=[1 0 1 1 1 1 1];
  % no gap between sdend and ssupdat
  disp_p.y.border=0.05;
  
  disp_p.items={{4,4,'data','row_center_and_normalize'},...
                {4,1,'gdend'},...
                {4,3,'gacc','vert',4},...
                {4,6,'gdist'},...
                {4,7,'colorbar','vert','for',4,6,6},...
                {1,4,'sdend'},...
                {2,4,'ssupdat'},...
                {2,3,'ssupacc','vert',4},...
                {3,4,'sdesc','horizontal',4},...
                {5,4,'colorbar','horizontal','for',4,4,6},...
                {6,4,'sdist'},...
                {6,5,'colorbar','vertical','for',6,4,6}};
  %%%% FINISH parameters!!!!
 case 'dends'
  disp_p.x.sizes=[0.7 0.1 3]; 
  % gdend, gsupdat, gacc, data
  disp_p.x.gaps=[1 1 1 1];
  % no gap between gdend and gsupdat
  disp_p.x.border=0.05;
  
  disp_p.y.sizes=[0.7 0.2 0.3 1 0.1];
  % sdend, ssupdat, sdesc, data, data colorbar
  disp_p.y.gaps=[1 0 1 1 1 1 1];
  % no gap between sdend and ssupdat
  disp_p.y.border=0.05;
  
  disp_p.items={{4,3,'data','row_center_and_normalize'},...
                {4,1,'gdend'},...
                {4,2,'gacc','vert',8},...
                {1,3,'sdend'},...
                {2,3,'ssupdat'},...
                {2,2,'ssupacc','vert',8},...
                {3,3,'sdesc','horizontal',8},...
                {5,3,'colorbar','horizontal',...
                 [1 11.5 22 32.5 43 53.5 64],...
                 {'-3\sigma','-2\sigma','-1\sigma','0','+1\sigma','+2\sigma','+3\sigma'},6},...
                {1:2,1,'ssuplegend',2,8,6}};
  
 case 'jun-reduced'
  disp_p.x.sizes=[0.5 0.025 3]; 
  % gdend, data
  disp_p.x.gaps=[1 1 0.2 1];
  % no gap between gdend and gsupdat
  disp_p.x.border=0.05;
  
  disp_p.y.sizes=[0.7 0.4 1]; % 0.08];
                              % sdend, ssupdat, sdesc, data, data colorbar
  disp_p.y.gaps=[1 0 1 2 3];
  % no gap between sdend and ssupdat
  disp_p.y.border=0.1;
  
  disp_p.items={{2,3,'ssupdat'},...
                {3,3,'data','row_center_and_normalize'},...
                {3,1,'gdend','reduced_big',1},...
                {1,3,'sdend','all',1},...
                {2,2,'ssupacc','vert',8},...
                {1:2,1,'ssuplegend',2,8,6}}; %,...
                                             %                {4,3,'colorbar','horizontal',...
                                             %                    [1 11.5 22 32.5 43 53.5 64],...
                                             %                    {'-3\sigma','-2\sigma','-1\sigma','0','+1\sigma','+2\sigma','+3\sigma'},6}};
 case 'jun-reduced-sdesc'
  disp_p.x.sizes=[0.8 0.15 3]; 
  % gdend, data
  disp_p.x.gaps=[1 1 0.2 1];
  % no gap between gdend and gsupdat
  disp_p.x.border=0.05;
  
  disp_p.y.sizes=[0.7 0.4 0.3 1]; % 0.08];
                                  % sdend, ssupdat, sdesc, data, data colorbar
  disp_p.y.gaps=[1 0 1 1 2 3];
  % no gap between sdend and ssupdat
  disp_p.y.border=0.1;
  
  disp_p.items={{2,3,'ssupdat'},...
                {4,3,'data','row_center_and_normalize'},...
                {4,1:2,'gdend','reduced_big',1},...
                {1,3,'sdend','all',1},...
                {2,2,'ssupacc','vert',8},...
                {1:2,1,'ssuplegend',2,8,6,0,{'Interpreter','none'}},...
                {3,3,'sdesc','horizontal',8,[],0,1,{'HorizontalAlignment','Left'}}}; 

  
 case 'jun-reduced-only-sdend'
  disp_p.x.sizes=[0.4 3]; 
  % gdend, data
  disp_p.x.gaps=[1 1 1];
  % no gap between gdend and gsupdat
  disp_p.x.border=0.05;
  
  disp_p.y.sizes=[0.2 1 0.08];
  % sdesc, data, data colorbar
  disp_p.y.gaps=[1 1 1];
  % no gap between sdend and ssupdat
  disp_p.y.border=0.1;
  
  disp_p.items={{1,2,'sdesc','horizontal',14},...
                {2,2,'data','row_center_and_normalize'},...
                {2,1,'gdend','all',1},...
                {3,2,'colorbar','horizontal',...
                 [1 11.5 22 32.5 43 53.5 64],...
                 {'-3\sigma','-2\sigma','-1\sigma','0','+1\sigma','+2\sigma','+3\sigma'},6}};

 case 'reduced'
  disp_p.x.sizes=[0.4 0.025 2.5]; 
  % gdend, data
  disp_p.x.gaps=[1 1 0.2 1];
  % no gap between gdend and gsupdat
  disp_p.x.border=0.05;
  
  disp_p.y.sizes=[0.7 0.6 1 0.06];
  % sdend, ssupdat, sdesc, data, data colorbar
  disp_p.y.gaps=[1 0 1 2 3];
  % no gap between sdend and ssupdat
  disp_p.y.border=0.1;
  
  disp_p.items={{2,3,'ssupdat'},...
                {3,3,'data','row_center_and_normalize'},...
                {3,1,'gdend'},...
                {1,3,'sdend'},...
                {2,2,'ssupacc','vert',8},...
                {4,3,'colorbar','horizontal',...
                 [1 11.5 22 32.5 43 53.5 64],...
                 {'-3','-2','-1','0','+1','+2','+3'},6},...
                {1:2,1,'ssuplegend',2,8,6}};

  
 case 'reduced2'
  disp_p.x.sizes=[0.4 0.025 3]; 
  % gdend, data
  disp_p.x.gaps=[1 1 0.2 1];
  % no gap between gdend and gsupdat
  disp_p.x.border=0.05;
  
  disp_p.y.sizes=[0.7 0.2 1 0.1];
  % sdend, ssupdat, sdesc, data, data colorbar
  disp_p.y.gaps=[1 0 1 2 3];
  % no gap between sdend and ssupdat
  disp_p.y.border=0.1;
  
  disp_p.items={{2,3,'ssupdat'},...
                {3,3,'data'},... %,'row_center_and_normalize'},...
                {3,1,'gdend'},...
                {1,3,'sdend'},...
                {2,2,'ssupacc','vert',8},...
                {4,3,'colorbar','horizontal',...
                 [1:(64-1)/(13-5):64],...
                 {num2str((5:13)')},6},...
                {1:2,1,'ssuplegend',2,8,6}};
  
 case 'sdend'
  disp_p.x.sizes=[1]; 
  % sdend (width)
  disp_p.x.gaps=[1 1];
  disp_p.x.border=0.05;
  
  disp_p.y.sizes=[0.5 0.1];
  % sdend, ssupdat
  disp_p.y.gaps=[1 0 1];
  % no gap between sdend and ssupdat
  disp_p.y.border=0.1;
  
  disp_p.items={{1,1,'sdend','all',1},...
                {2,1,'ssupdat'}};
  
 case 'sdendleg'
  disp_p.x.sizes=[0.175 1]; 
  % sdend (width)
  disp_p.x.gaps=[1 1 1];
  disp_p.x.border=0.05;
  
  disp_p.y.sizes=[0.25 0.06];
  % sdend, ssupdat
  disp_p.y.gaps=[1 0 1];
  % no gap between sdend and ssupdat
  disp_p.y.border=0.1;
  
  disp_p.items={{1,2,'sdend','all',1},...
                {2,2,'ssupdat'},...
                {1:2,1,'ssuplegend',1,14,12}};

 case 'datsup_gdend'
  disp_p.x.sizes=[0.3 1]; 
  % sdend (width)
  disp_p.x.gaps=[1 1 1];
  disp_p.x.border=0.05;
  
  disp_p.y.sizes=[0.1 0.5 0.02];
  % sdend, ssupdat
  disp_p.y.gaps=[1 1 1 1];
  % no gap between sdend and ssupdat
  disp_p.y.border=0.1;
  
  disp_p.items={{1,1,'ssupacc','vert',14},...
                {2,1,'gdend','all',1},...
                {1,2,'ssupdat'},...
                {2,2,'data','row_center_and_normalize'},...
                {3,2,'colorbar','horizontal',...
                 [1 11.5 22 32.5 43 53.5 64],...
                 {'-3\sigma','-2\sigma','-1\sigma','0','+1\sigma','+2\sigma','+3\sigma'},6}};
  
 case 'datsup'
  disp_p.x.sizes=[0.3 1]; 
  % sdend (width)
  disp_p.x.gaps=[1 1 1];
  disp_p.x.border=0.05;
  
  disp_p.y.sizes=[0.1 0.5 0.02];
  % sdend, ssupdat
  disp_p.y.gaps=[1 1 1 1];
  % no gap between sdend and ssupdat
  disp_p.y.border=0.1;
  
  disp_p.items={{1,1,'ssupacc','vert',8},...
                {2,1,'ssuplegend',2,8,6},...
                {1,2,'ssupdat'},...
                {2,2,'data','row_center_and_normalize'},...
                {3,2,'colorbar','horizontal',...
                 [1 11.5 22 32.5 43 53.5 64],...
                 {'-3\sigma','-2\sigma','-1\sigma','0','+1\sigma','+2\sigma','+3\sigma'},6}};
 
 case 'datsupnames'
  disp_p.x.sizes=[0.3 0.1 1]; 
  % sdend (width)
  disp_p.x.gaps=[1 1 1 1];
  disp_p.x.border=0.05;
  
  disp_p.y.sizes=[0.1 0.1 0.5 0.02];
  % sdend, ssupdat
  disp_p.y.gaps=[1 1 1 1];
  % no gap between sdend and ssupdat
  disp_p.y.border=0.1;
  
  disp_p.items={{1,2,'ssupacc','vert',8},...
                {1:2,1,'ssuplegend',2,8,6},...
                {1,3,'ssupdat'},...
                {2,3,'sdesc','horizontal',6},...
                {3,3,'data','row_center_and_normalize'},...
                {3,1:2,'gacc','vertical',10},...
                {4,3,'colorbar','horizontal',...
                 [1 11.5 22 32.5 43 53.5 64],...
                 {'-3\sigma','-2\sigma','-1\sigma','0','+1\sigma','+2\sigma','+3\sigma'},6}};
 
 case 'datorigsupnames'
  disp_p.x.sizes=[0.3 0.1 1]; 
  % sdend (width)
  disp_p.x.gaps=[1 1 1 1];
  disp_p.x.border=0.05;
  
  disp_p.y.sizes=[0.1 0.1 0.5 0.02];
  % sdend, ssupdat
  disp_p.y.gaps=[1 1 1 1];
  % no gap between sdend and ssupdat
  disp_p.y.border=0.1;
  
  disp_p.items={{1,2,'ssupacc','vert',8},...
                {1:2,1,'ssuplegend',2,8,6},...
                {1,3,'ssupdat'},...
                {2,3,'sdesc','horizontal',6},...
                {3,3,'dataorig'},...
                {3,1:2,'gacc','vertical',10},...
                {4,3,'colorbar','horizontal',...
                 [1 11.5 22 32.5 43 53.5 64],...
                 {'-3\sigma','-2\sigma','-1\sigma','0','+1\sigma','+2\sigma','+3\sigma'},6}};

 case 'datorigsup'
  disp_p.x.sizes=[0.3 1]; 
  % sdend (width)
  disp_p.x.gaps=[1 1 1];
  disp_p.x.border=0.05;
  
  disp_p.y.sizes=[0.1 0.5 0.1];
  % sdend, ssupdat
  disp_p.y.gaps=[1 1 1 1];
  % no gap between sdend and ssupdat
  disp_p.y.border=0.1;
  
  disp_p.items={{1,1,'ssupacc','vert',8},...
                {2,1,'ssuplegend',2,8,6},...
                {1,2,'ssupdat'},...
                {2,2,'dataorig',[5 13]},...
                {3,2,'colorbar','horizontal',...
                 [1+63/8*(0:8)],...
                 {'5','6','7','8','9','10','11','12','13'},6}};
  
  
 
 case 'datsupgsup'
  disp_p.x.sizes=[0.2 0.05 1]; 
  % sdend (width)
  disp_p.x.gaps=[1 1 0.2 1];
  disp_p.x.border=0.05;
  
  disp_p.y.sizes=[0.1 0.5 0.1];
  % sdend, ssupdat
  disp_p.y.gaps=[1 1 1 1];
  % no gap between sdend and ssupdat
  disp_p.y.border=0.1;
  
  disp_p.items={{1,1:2,'ssupacc','vert',8},...
                {2,1,'ssuplegend',1,8,6},...
                {2,2,'gsupdat'},...
                {1,3,'ssupdat'},...
                {2,3,'data','row_center_and_normalize'},...
                {3,3,'colorbar','horizontal',...
                 [1 11.5 22 32.5 43 53.5 64],...
                 {'-3\sigma','-2\sigma','-1\sigma','0','+1\sigma','+2\sigma','+3\sigma'},6}};
  
 case 'datorigsupgsup'
  disp_p.x.sizes=[0.2 0.05 1]; 
  % sdend (width)
  disp_p.x.gaps=[1 1 0.2 1];
  disp_p.x.border=0.05;
  
  disp_p.y.sizes=[0.1 1 0.1];
  % sdend, ssupdat
  disp_p.y.gaps=[1 1 1 1];
  % no gap between sdend and ssupdat
  disp_p.y.border=0.1;
  
  disp_p.items={{1,1:2,'ssupacc','vert',8},...
                {2,1,'ssuplegend',1,8,6},...
                {2,2,'gsupdat'},...
                {1,3,'ssupdat'},...
                {2,3,'dataorig',[5 13]},...
                {3,3,'colorbar','horizontal',...
                 [1+63/8*(0:8)],...
                 {'5','6','7','8','9','10','11','12','13'},6}};
 case 'dendsnames'
  disp_p.x.sizes=[1.5 0.8 0.025 5.8]; 
  disp_p.x.gaps=[1 1 1 0.2 1];
  disp_p.x.border=0.05;
  
  disp_p.y.sizes=[0.7 0.8 0.8 4 0.2];
  disp_p.y.gaps=[1 0 1 1 1 1];
  disp_p.y.border=0.1;
  
  disp_p.items={{2,4,'ssupdat'},...
                {3,4,'sdesc','horizontal',3,[],0.5,[],{'HorizontalAlignment','Left'}},...
                {4,4,'data','row_center_and_normalize'},...
                {4,1,'gdend','all',0.5},...
                {4,2,'gacc','vert',3},...
                {1,4,'sdend','all',0.5},...
                {2,3,'ssupacc','vert',6},...
                  {5,4,'colorbar','horizontal',...
                   [1 11.5 22 32.5 43 53.5 64],...
                   {'-3\sigma','-2\sigma','-1\sigma','0','+1\sigma','+2\sigma','+3\sigma'},6},...
                  {1:3,1,'ssuplegend',2,8,6}};

  case 'code'
   disp_p=struct('x',struct('sizes',[0.1 0.8 0.025 5.8],'gaps',[ 1 1 1 0.2 1],'border',0.05),...
                 'y',struct('sizes',[1.5 0.5 0.1 2],'gaps',[ 1 0 1 1 1],'border',0.1),...
                 'items',...
                 {{{2,4,'ssupdat'},...
                   {3,4,'sdesc','horizontal',10,[],0,[],{'HorizontalAlignment','Left'}},...
                   {4,4,'dataorig'},...
                   {4,1,'gdend','all',0.5},...
                   {4,2,'gacc','vert',10},...
                   {1,4,'sdend','all',0.5},...
                   {2,3,'ssupacc','vert',6},...
                   {1:3,1,'ssuplegend',2,8,6}}});
   
 case 'snp_fxa'
  disp_p=struct('x',struct('sizes',[0.3 0.1 0.03 1 0.5 0.5],'gaps',[1 1 1 1 1 1 1],'border',0.1),...
                'y',struct('sizes',[0.4 2 0.1],'gaps',[1 1 1 1],'border',0.1),...
                'items',...
                {{{1,1,'ssupacc','vert',8},...
                  {2,1,'ssuplegend',2,8,6},...
                  {1,4,'ssupdat'},...
                  {2,4,'dataorig',[-1.5 1.5]},...
                  {2,2,'chrn','vert',8,-0.5},...
                  {2,3,'chrcyto'},...               
                  {3,4,'colorbar','horizontal',[1+63/6*(0:6)],{'-1.5','-1','-0.5','0','0.5','1','1.5'},6},...
                  {2,5,'fxascore',1},...
                  {2,6,'fxascore',2}}});
  
 case 'snp_pvs'
  disp_p=struct('x',struct('sizes',[0.3 0.1 0.03 1 0.5 0.5],'gaps',[1 1 1 1 1 1 1],'border',0.05),...
                'y',struct('sizes',[0.4 2 0.1],'gaps',[1 1 1 1],'border',0.1),...
                'items',...
                {{{1,1,'ssupacc','vert',8},...
                  {2,1,'ssuplegend',2,8,6},...
                  {1,4,'ssupdat'},...
                  {2,4,'dataorig',[-1.5 1.5]},...
                  {2,2,'chrn','vert',8,-0.5},...
                  {2,3,'chrcyto'},...               
                  {3,4,'colorbar','horizontal','for',2,4,4,6},...
                  {2,5,'pvs',1,1,0.25},...
                  {2,6,'pvs',2,1,0.25}}});
  
 case 'snp'
  disp_p=struct('x',struct('sizes',[0.1 0.03 1],'gaps',[1 1 1 1],'border',0.1),...
                'y',struct('sizes',[ 2 0.05],'gaps',[1 1 2],'border',0.1),...
                'items',...
                {{...
                    {1,3,'dataorig',[-1 1]},...
                    {1,1,'chrn','vert',8,-0.5},...
                    {1,2,'chrcyto'},...               
                    {2,3,'colorbar','horizontal',[1+63/4*(0:4)],{'-1','-0.5','0','0.5','1'},6},...
                 }});
 
 case 'lohsup'
  disp_p=struct('x',struct('sizes',[0.1 0.03 1],'gaps',[1 1 1 1],'border',0.1),...
                'y',struct('sizes',[ 0.1 2 0.05],'gaps',[1 1 1 2],'border',0.1),...
                'items',...
                {{...
                    {1,3,'ssupdat'},...
                    {2,3,'dataorig',[0 1],[ 1 1 0; 0 0 1]},...
                    {2,1,'chrn','vert',8,-0.5},...
                    {2,2,'chrcyto'},...               
                 }});
 
 case 'snpsup'
  disp_p=struct('x',struct('sizes',[0.1 0.03 1],'gaps',[1 1 1 1],'border',0.1),...
                'y',struct('sizes',[ 0.1 2 0.05],'gaps',[1 1 1 2],'border',0.1),...
                'items',...
                {{...
                    {1,3,'ssupdat'},...
                    {2,3,'dataorig',[-1 1]},...
                    {2,1,'chrn','vert',8,-0.5},...
                    {2,2,'chrcyto'},...               
                    {3,3,'colorbar','horizontal',[1+63/4*(0:4)],{'-1','-0.5','0','0.5','1'},6},...
                 }});
  
 case 'snpcyto'
  disp_p=struct('x',struct('sizes',[0.1 0.03 0.03 1],'gaps',[1 1 1 1 1],'border',0.1),...
                'y',struct('sizes',[ 2 0.1],'gaps',[1 1 1],'border',0.1),...
                'items',...
                {{...
                    {1,4,'dataorig',[-1.5 1.5]},...
                    {1,1,'chrn','vert',8,-0.5},...
                    {1,2,'chrcyto'},...               
                    {1,3,'chrcyto',1},...               
                    {2,4,'colorbar','horizontal',[1+63/6*(0:6)],{'-1.5','-1','-0.5','0','0.5','1','1.5'},6},...
                 }});
  
 case 'snpcytosup'
  disp_p=struct('x',struct('sizes',[0.1 0.03 0.03 1],'gaps',[1 1 1 1 1],'border',0.15),...
                'y',struct('sizes',[ 0.1 2 0.1],'gaps',[1 1 1 1],'border',0.15),...
                'items',...
                {{...
                    {1,4,'ssupdat'},...
                    {2,4,'dataorig',[-1.5 1.5]},...
                    {2,1,'chrn','vert',8,-0.5},...
                    {2,2,'chrcyto'},...               
                    {2,3,'chrcyto',1},...               
                    {3,4,'colorbar','horizontal',[1+63/6*(0:6)],{'-1.5','-1','-0.5','0','0.5','1','1.5'},6},...
                 }});
  
   
 otherwise
  disp_p.x.sizes=[3]; 
  % data
  disp_p.x.gaps=[1 1];
  % no gap between gdend and gsupdat
  disp_p.x.border=0.05;
  
  disp_p.y.sizes=[1 0.1];
  % data, data colorbar
  disp_p.y.gaps=[1 1 1];
  % no gap between sdend and ssupdat
  disp_p.y.border=0.05;
  
  disp_p.items={{1,1,'data','row_center_and_normalize'},...
                {2,1,'colorbar','data'}};
end









